### ISSUE TITLE
Why move to axios?

### ISSUE THREAD

**Issue by XuluWarrior** [ethanent/phin#92]
What was wrong with the previous (centra based) code?

Is there a security issue that required this drastic change?
Otherwise why not leave the code as is?

**Comment by yetzt** [comment]
> The lightweight Node.js HTTP client

this should be changed since it's a good 2 megabytes now.

**Comment by ethanent** [comment]
The intention was for v4 to serve as a more minimal library for Axios compatibility while providing a similar and mostly backwards compatible API.

I see the feedback and am open to discontinuing v4 (deprecating it, I guess?) and releasing a new version of v3 which includes fixes.

**Comment by yetzt** [comment]
Since you have not elaborated what the reasons for deprecating the project were in the first place, i can only assume you can not afford the time or energy to maintain it. Please correct me here if i'm wrong. Whatever your reasons are, i'm certain they are valid and stepping down from a project to put other priorities forward is absolutely fine.

However, i wish there had been an announcement before deprecating the project. I do not know if you have made any non-public effort to find a new maintainer for phin. My hope would be for you to find a new maintainer instead of the efforts that have been made. 

I think i understand why you put out the "axios-version", but since the "selling-point" of phin has always been it's lightweightedness i feel this was misguided.

Anyway, there are still ways forward, if you do not want to continue to be the maintainer of phin (or contribute at a lesser capacity): Find a new maintainer to care about issues, pull requests, security reports and the boring day-to-day bits, maybe while staying the owner of the project and retain control of the package. 

I can think about offering my help to do at least some "spring cleaning" with regards to the open issues and pull requests.

**Comment by ethanent** [comment]
That's right, it's mainly due to time constraints on my end and not using Node.js regularly anymore. I appreciate your suggestions and the offer to help with maintaining the library.

Keep an eye out for future updates. I'm hoping to officially pass the torch to new maintainer(s) soon, after wrapping up some things.
